# Generated by Django 5.1.6 on 2025-02-17 12:15

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=128)),
                ('roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('admin', 'Admin'), ('cinemaphile', 'Cinemaphile')], max_length=32), default=list, size=None)),
                ('city', models.CharField(max_length=128, null=True)),
                ('country', models.CharField(max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('telegram_id', models.CharField(max_length=128, null=True)),
            ],
        ),
    ]
