[project]
name = "funnyalexander"
version = "1.0.0"
description = "A random movie for day"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.1.6",
    "psycopg2-binary>=2.9.10",
]

[dependency-groups]
lint = [
    "pre-commit>=4.1.0",
]
