"""Added username field with server_default into User

Revision ID: 6b8962121782
Revises: aafd80e31204
Create Date: 2024-06-21 12:49:22.012389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6b8962121782'
down_revision: Union[str, None] = 'aafd80e31204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user', 
        sa.Column(
            'username', 
            sqlmodel.sql.sqltypes.AutoString(), 
            nullable=True,
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
