"""user.username is unique and index

Revision ID: ec9e99a2471e
Revises: 6b8962121782
Create Date: 2024-06-21 17:37:14.244352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec9e99a2471e'
down_revision: Union[str, None] = '6b8962121782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'user', 
        'username',
        existing_type=sa.VARCHAR(),
        nullable=False
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.alter_column(
        'user', 
        'username',
        existing_type=sa.VARCHAR(),
        nullable=True
    )
    # ### end Alembic commands ###
